#!/bin/bash

## Directory of compilation scripts and executables 
oneDmgcm=/home/s1215319/mgcm/oneDmgcm

########################
## L-BFGS-B files 
######################## 

lbfgsb=lbfgsb.f
linpack=linpack.f
blas=blas.f
timer=timer.f

#########################
## 1-D Routines
#########################
## Enter 1-D model directory
cd $oneDmgcm

## Compile the 1-D model
./makegcm_gfortran -d 1x1x25 -p mars t -16 testphys1d 

## Back to L-BFGS-B directory
cd - 

## Compile the L-BFGS-B scripts 
gfortran -c lbfgsb_mod.f90 
gfortran OPTIMIZE/$lbfgsb OPTIMIZE/$linpack OPTIMIZE/$blas OPTIMIZE/$timer lbfgsb_mod.o lbfgsb_init.f90 run.f -o run.e
