#!/bin/bash

## Directory of compilation scripts and executables 
oneDmgcm=/home/s1215319/mgcm/oneDmgcm

########################
## L-BFGS-B files 
######################## 

lbfgsb=lbfgsb.f
linpack=linpack.f
blas=blas.f
timer=timer.f

#########################
## 1-D Routines
#########################
## Enter 1-D model directory
cd $oneDmgcm

## Select number of tracers
echo "Number of TRACER (16 or 27)?"
read nqmx 

## Compile the 1-D model
./makegcm_gfortran -d 1x1x25 -p mars -t $nqmx -lbfgsb testphys1d 

## Update the traceur.def file 
sed -i "1s/.*/$nqmx/" traceur.def


## Back to L-BFGS-B directory
cd - 


# Edit the module file
sed -i '/INTEGER, PARAMETER :: nqmx =/c\INTEGER, PARAMETER :: nqmx ='$nqmx lbfgsb_mod.f90 



## Compile the L-BFGS-B scripts 
gfortran -c lbfgsb_mod.f90 
gfortran OPTIMIZE/$lbfgsb OPTIMIZE/$linpack OPTIMIZE/$blas OPTIMIZE/$timer lbfgsb_mod.o makeinput.f90 lbfgsb_init.f90 run.f -o run.e
